apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello-w-params
spec:
  params:
  - name: myname
    type: string
  steps:
    - name: hello
      image: ubuntu
      script: |
        #!/bin/bash
        echo "Hello $(params.myname)!"